name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker buildx build --file Dockerfile --output type=image,name=zhikariz/weather-app:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: zhikariz
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: latest 

    - name: SSH into the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Pull the lastest Docker image
          docker pull zhikariz/weather-app:latest

          # Stop and remove the existing container (if any)
          docker-compose -f /root/weather-app/docker-compose.yml down

          # Start the updated container
          docker compose -f /root/weather-app/docker-compose.yml up -d